//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public int Id { get; set; }
        public int prescription_id { get; set; }
        public string patient_name { get; set; }
        public string name_on_card { get; set; }
        public Nullable<int> card_number { get; set; }
        public Nullable<int> exp { get; set; }
        public Nullable<int> ccv { get; set; }
        public int amount { get; set; }
    
        public virtual Prescription Prescription { get; set; }
    }
}
