//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deseases_Doctors
    {
        public int dd_ID { get; set; }
        public int Desease_ID { get; set; }
        public int Doctor_ID { get; set; }
    
        public virtual Desease Desease { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
