//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHealthDetail
    {
        public int Ph_Id { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> HeartRate { get; set; }
        public Nullable<int> BodyTemperature { get; set; }
        public Nullable<int> Glucose { get; set; }
        public string Allergies { get; set; }
        public string Diseases { get; set; }
        public System.DateTime LastVisit { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
