//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ward
    {
        public int Ward_No { get; set; }
        public int Hospital_ID { get; set; }
        public int Ward_Status { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
